testing_mode = true
payment_provider = "stripe" #bmac if using Buy Me A Coffee
stripe_api_key_test = "rk_test_51Ok4HNSI6bAqaFSzWaU2uDxhsHdfMgj4eYq2d157F92l0B9vj3GzJ72J2lyfFb0q4tLngvdaQsRDoNFpJFgCKk36009g9zXbmc" #only needed if using Stripe
stripe_api_key = "sk_live_..." #only needed if using Stripe
stripe_link = "https://buy.stripe.com/..." #only needed if using Stripe
stripe_link_test = "https://buy.stripe.com/test_6oEbMO5Wl2iq4Ug5kk" #only needed if using Stripe
client_id = "559367153315-nf0vkid3t93u6g0vsfuf54gb1jmjlebn.apps.googleusercontent.com"
client_secret = "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"
redirect_url_test = 'https://droptable.onrender.com/'
redirect_url = "https://droptable.onrender.com/"
bmac_api_key = "ey..." #only needed if using buy me a coffee
bmac_link = "https://www.buymeacoffee.com/..." #only needed if using buy me a coffee
